### PR TITLE
event on connect; web api instead of axios; method for direct channels

### PR DESCRIPTION
**Pull request by brocoders-vlad-rasenko**

### CODE REVIEW

**Comment by slvnperron** [comment]
@brocoders-vlad-rasenko Thanks for the PR!

Could you please sign the CLA above so I can merge this?

(Do ping me afterward so I get notified)

**Comment by slvnperron** [comment]
@brocoders-vlad-rasenko Sorry I can't see your signature in the list and the CLA bot says it is not signed. Are you sure you clicked the correct link?

https://cla-assistant.io/botpress/botpress-slack?pullRequest=23

**Comment by brocoders-vlad-rasenko** [comment]
@slvnperron I don't know why the last time it did not work, now should signed

**Comment by slvnperron** [comment]
@brocoders-vlad-rasenko Great! thanks

**Pull request merged**
